### ISSUE TITLE
speed_aggregate returns sum if all weights are zero

### ISSUE THREAD

**Issue by orichters** [pik-piam/luscale#1]
In `remind2`, we had [the problem](https://github.com/pik-piam/remind2/issues/287) that in [speed_aggregate](https://github.com/pik-piam/luscale/blob/master/R/speed_aggregate.R#L64), weighted average defaults to a sum if all region values are `0` in some years (which happened for technology that were only deployed later). We "fixed" it by [setting them to 1E-32 instead of 0](https://github.com/pik-piam/remind2/pull/289), but maybe a more elegant solution is possible. This implies that a simple average is taken instead of a weighted for non-deployed technologies.

For example, speed_aggregate could use the sum only if weight is zero for all time-steps, but I have no clue where this function is used and how, so somebody with more knowledge may step in. Tagging @tscheypidi as the author of this function.

**Comment by tscheypidi** [comment]
`speed_aggregate` has been superseded by [`toolAggregate`](https://github.com/pik-piam/madrat/blob/master/R/toolAggregate.R) from the `madrat` package which provides an argument `mixed_aggregation` to control such behavior. I would recommend to switch to this function instead.

**Comment by orichters** [comment]
Thanks. In case of all `0` weights, `toolAggregate` returns `0` as average. I wouldn't dispute that behavior as there is not "just" way to define `0/0` as `0`, `1` or `NA`.
